name: CI

on: [push]

jobs:
  build-phpunit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPUnit Run Tests and Coverage
        uses: php-actions/phpunit@v3
        with:
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit.xml
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage